### ISSUE TITLE
pretrained models

### ISSUE THREAD

**Issue by rafaz0300** [farazBhatti/gun_detection#1]
can i ask for the pretrained models.

**Comment by rafaz0300** [comment]
I meant that download link given in the readme is not working

**Comment by rafaz0300** [comment]
can you please reupload

**Comment by rafaz0300** [comment]
can you please email me at rafaz0300@gmail.com as your download link is not accessible

**Comment by farazBhatti** [comment]
@rafaz0300 ive updated the link, you can also download it [here](https://drive.google.com/file/d/1xwaN6hdbW6u2f01E95AYq_rX3hdNARCU/view?usp=sharing) . file is a little large for email.
